# -*- coding: utf-8 -*-
"""Samandar.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uoQI_QjFktb166Y9uvM2InT7s7-Hzz4x
"""



import numpy as np


# 1. Massiv yaratish

array_1d = np.array ([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# 2. Matematik operatsiyalar

sum_array = np.sum(array_1d)

mean_array = np.mean(array_1d)

product_array = np.prod(array_1d)

print("1D Massiv: ", array_1d)

print("2D Massiv:\n", array_2d)

print("Massivlar yig'indisi: ", sum_array)

print("O'rtacha: ", mean_array)

print("Ko'paytma: ", product_array)

import pandas as pd
#1.DataFrame yaratish
[]
data = {



'Ism': ['Ruhammad', 'Javohir', 'Samandar', 'Ozodbek', 'Shoxruh', 'Sadulla', 'Anvarjon', 'Omadbek', 'Farrux', 'Sirojiddin'],
'Yoshi': [19,22, 19, 19,19,20,19,20,20,19],
'Shahar': ['Fargona', 'Fargona', 'Fargona', 'Fargona', 'Fargona', 'Qoqon', 'Namangan', 'Qoqon', 'Fargona', 'Andijon']
}
df=pd.DataFrame(data)

#2.Ma'lumotlar

print(df)

#3. Filtrlash

young_people=df[df['Yoshi']<20]

print("20 yoshdan kichiklar:\n", young_people)

#4. O'zgartirish
df['Yoshi']-=1
#har bir shaxs yoshidan ini ayirish.

print("Yangilangan dataframe:\n", df)

#5. Farg'onaliklarni chiqarish
fargonaliklar =df [df['Shahar'] == 'Fargona']

print("Farg'onaliklar:\n", fargonaliklar)

#6. Excel formatda saqlash.
df.to_excel('642_23.xlsx', index=True, sheet_name= "642_23")

"""# Новый раздел"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,8,10,7])

y=np.array([0,350,52,68])

plt.plot(x,y,)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,50,42,100])

y=np.array([0,350,52,68])

plt.plot(x,'o:b' )

plt.plot(y, 'o:r')

plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Yurak shakli uchun parametrik tenglamalar
t = np.linspace(0, 2 * np.pi, 1000)
x = 16 * np.sin(t) ** 3
y = 13 * np.cos(t) - 5 * np.cos(2 * t) - 2 * np.cos(3 * t) - np.cos(4 * t)

# Yurakni chizish
plt.plot(x, y, color="red")
plt.fill(x, y, color="red")  # Yurak ichini to'ldirish
plt.axis("equal")  # Ko'rinishni teng o'lchamda qilish
plt.axis("off")  # Koordinatalarni o'chirish
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,50,42,100])

plt.plot(x, marker='o', ms=20 , mec='r')

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x=np.array([0,50,42,10,16])

y=np.array([0,9,20,45,4])

plt.plot(x,y)
plt.xlabel("Overs")
plt.ylabel("Runs")
plt.title("Sport Data", loc='left')
plt.grid()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['samandar','Muhammadjon','Ozodbek','Anvarjon'])
y=np.array([10,7,4,5,])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([45,15,50,10])
mylabels=["olma","anor","shaftoli","bodom"]
plt.pie(y, labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([45,15,50,10])
mylabels=["olma","anor","shaftoli","bodom"]
myexplode=[0.2,0,0,0]
plt.pie(y, labels=mylabels,startangle=90, explode=my)
plt.show()